// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnuclZvrLdvdUaG3v7gvjw2QB4ZR4TYjI',
    appId: '1:1025815489213:web:a566654a5acb685c5f25d4',
    messagingSenderId: '1025815489213',
    projectId: 'fitness-app-76b9a',
    authDomain: 'fitness-app-76b9a.firebaseapp.com',
    storageBucket: 'fitness-app-76b9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC81H-6g9m0mjsJfr-_99hiIO86HjehcH0',
    appId: '1:1025815489213:android:c9416f5470cbefb75f25d4',
    messagingSenderId: '1025815489213',
    projectId: 'fitness-app-76b9a',
    storageBucket: 'fitness-app-76b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUINcv7tRw2YB6gbnz6ypV6jI9Nm4sdKs',
    appId: '1:1025815489213:ios:368abbd6800458095f25d4',
    messagingSenderId: '1025815489213',
    projectId: 'fitness-app-76b9a',
    storageBucket: 'fitness-app-76b9a.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
